services:
  db:
    image: mysql:8.0
    ports:
      - 3610:3306
    volumes:
      - retail_test:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=retail_test
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8610:80
    depends_on:
      - db
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=root
volumes:
  retail_test: